skill_categories:
  ARMOUR:
    - IRON_HELMET
    - IRON_CHESTPLATE
    - IRON_LEGGINGS
    - IRON_BOOTS
  BLADESMITHING:
    - IRON_SWORD
    - IRON_SPEAR
    - IRON_AXE
  PICKAXE:
    - IRON_PICKAXE
    - IRON_SHOVEL
  AXE:
    - IRON_AXE
  HOE:
    - IRON_HOE
  BOW:
    - BOW

gainable_enchantments:
  ARMOUR:
    - PROTECTION
    - UNBREAKING
  BLADESMITHING:
    - SHARPNESS
    - UNBREAKING
  PICKAXE:
    - EFFICIENCY
    - UNBREAKING
  AXE:
    - EFFICIENCY
    - UNBREAKING
  HOE:
    - FORTUNE
    - UNBREAKING
  BOW:
    - POWER
    - UNBREAKING

gainable_xp:
  ARMOUR:
    IRON_HELMET: 0.625
    IRON_BOOTS: 0.5
    IRON_CHESTPLATE: 1
    IRON_LEGGINGS: 0.875
  BLADESMITHING:
    IRON_SWORD: 0.25
    IRON_AXE: 0.1
    IRON_SPEAR: 0.125
  PICKAXE:
    IRON_PICKAXE: 0.375
    IRON_SHOVEL: 0.125
  AXE:
    IRON_AXE: 0.375
  HOE:
    IRON_HOE: 0.375

disabled_recipes:
  - ENCHANTING_TABLE
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS
  - DIAMOND_SPEAR
  - DIAMOND_SHOVEL
  - DIAMOND_HOE

disabled_entities:
  - IRON_GOLEM

custom_unshaped_recipes:
  quartz:
    - diorite
  1quartz:
    - andesite
    - andesite
  brick 4:
    - bricks

custom_shaped_recipes:
  glowstone_dust 8:
    - redstone
    - redstone
    - redstone
    - redstone
    - glow_berries
    - redstone
    - redstone
    - redstone
    - redstone
  iron_horse_armor:
    - iron_ingot
    - air
    - air
    - iron_ingot
    - iron_block
    - iron_ingot
    - iron_ingot
    - air
    - iron_ingot
  golden_horse_armor:
    - gold_ingot
    - air
    - air
    - gold_ingot
    - gold_block
    - gold_ingot
    - gold_ingot
    - air
    - gold_ingot
  diamond_horse_armor:
    - diamond
    - air
    - air
    - diamond
    - diamond_block
    - diamond
    - diamond
    - air
    - diamond