skill_categories:
  ARMOUR:
    - IRON_HELMET
    - IRON_CHESTPLATE
    - IRON_LEGGINGS
    - IRON_BOOTS

gainable_enchantments:
  ARMOUR:
    - PROTECTION
    - UNBREAKING

gainable_xp:
  ARMOUR:
    IRON_HELMET: 0.625
    IRON_BOOTS: 0.5
    IRON_CHESTPLATE: 1
    IRON_LEGGINGS: 0.875