name: Maurice-SMP
version: '${version}'

main: io.github.skulli73.mauriceSMP.MauriceSMP
api-version: '26.1'

commands:
  addskillxp:
    description: Add Skill XP
    usage: /<command> <player>  <skill> <amount>
    permission: maurice-smp.skillmanagement
  skills:
    description: Show your skills
    usage: /<command>
  cf:
    description: Ciro-Fun Commands
    usage: /<command>

permissions:
  maurice-smp.*:
    description: Gives access to all Maurice-SMP commands
    children:
      maurice-smp.skillmanagement: true
  maurice-smp.skillmanagement:
    description: Allows you to manage skills for other players
    default: false
  maurice-smp.cf-admin:
    description: Admin permissions for CiroFun
    default: false
